name: docker

on:
  release:
    types: [ published ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - id: checkout
        name: Checkout
        uses: actions/checkout@v2
        
      - id: QEMU
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        
      - id: Buildx
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Get semantic version from file
        id: getSemver
        run: echo "::set-output name=semver::$(cat VERSION | tr -d ' \t\n\r' )"

      - name: Get current date
        id: getDate
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
        
      - id: DockerHub
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - id: push
        name: Build and push
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          push: true
          tags: techblog/deepstack-trainer:${{ steps.getSemver.outputs.semver }}
          build-args: |
            BUILD_DATE=${{ steps.getDate.outputs.date }}
            VERSION=${{ steps.getSemver.outputs.semver }}
          cache-from: |
            type=local,src=/tmp/.buildx-cache
            ghcr.io/tomerfi/switcher_webapi:early-access
          cache-to: type=local,dest=/tmp/.buildx-cache
          
